### ISSUE TITLE
Getting error discovering devices

### ISSUE THREAD

**Issue by jneilliii** [pywemo/pywemo#103]
First and foremost, thanks for a great library.  I have developed an OctoPrint-Plugin around it and one of my users is getting an error.  After further investigation it appears to be a problem with the pywemo discover_devices() call.  This is the error that they are getting.  Any advice as to what might be the root cause of this issue?

```
devices = pywemo.discover_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pywemo/discovery.py", line 22, in discover_devices
    ssdp_entries = ssdp.scan(st, max_entries=max_devices, match_mac=match_mac)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pywemo/ssdp.py", line 245, in scan
    if entry.description is not None:
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pywemo/ssdp.py", line 140, in description
    tree = ElementTree.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1651, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 357: ordinal not in range(128)
```

Issue found on my repository over [here](https://github.com/jneilliii/OctoPrint-WemoSwitch/issues/5).

**Comment by pavoni** [comment]
From the link on your repo looks like you've found a workround.

My guess is that some PnP device on your network is returning a description that isn't ascii, which i messing up the discovery code.

Since it probably isn't  a device that you want - you could probably just catch the exception and continue. So just catch the exception around this line.

https://github.com/pavoni/pywemo/blob/master/pywemo/ssdp.py#L140

**Comment by jneilliii** [comment]
Yeah thanks. I switched over to using direct discovery of the device via ip. That seems to have gotten around the issue.
