### ISSUE TITLE
Error importing when run at boot on raspberry pi

### ISSUE THREAD

**Issue by ghost** [pywemo/pywemo#140]
When testing my script, whether SSH'd in or in the console on the device itself, I encounter no problems. However, when running the script at boot on my pi (I've tried both rc.local and .bashrc), I get this error:

```
Traceback (most recent call last):
  File "/home/pi/IFTTT/wemo2.py", line 7, in <module>
    import pywemo
ModuleNotFoundError: No module named 'pywemo'
```

Could someone let me know what I'm doing wrong? The command I'm running, both manually and automatically, is `sudo python3 /home/pi/IFTTT/wemo2.py`.

```
print("\n4-button WeMo remote for Raspberry Pi")

# Imports
import RPi.GPIO as GPIO
import time
import pywemo

# Set the GPIO naming convention
GPIO.setmode(GPIO.BOARD)

# Turn off GPIO warnings
GPIO.setwarnings(False)

# GPIO button pins
but0 = 7
but1 = 11
but2 = 13
but3 = 15

# GPIO led pins
led0 = 12
led1 = 16
led2 = 18
led3 = 22

# Set but pins as input
GPIO.setup(but0, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(but1, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(but2, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(but3, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)

# Set led pins as output
GPIO.setup(led0, GPIO.OUT)
GPIO.setup(led1, GPIO.OUT)
GPIO.setup(led2, GPIO.OUT)
GPIO.setup(led3, GPIO.OUT)

# Turn on led pins
GPIO.output(led0, GPIO.HIGH)
GPIO.output(led1, GPIO.HIGH)
GPIO.output(led2, GPIO.HIGH)
GPIO.output(led3, GPIO.HIGH)

# Variables to hold button states
state0 = 0
state1 = 0
#state2 = 0
#state3 = 0

# Func to toggle the switch corresponding to a button
def trigger(button, switch):
	num = -1
	if button == but0:
		num = 0
	elif button == but1:
		num = 1
	elif button == but2:
		num = 2
	elif button == but3:
		num = 3

	print("Button", str(num), "pressed!")
	switch.toggle()
	while GPIO.input(button) == GPIO.HIGH:
		time.sleep(0.01)
	time.sleep(0.1)

# Func to blink button leds
def blink(num):
	GPIO.output(led0, GPIO.LOW)
	GPIO.output(led1, GPIO.LOW)
	GPIO.output(led2, GPIO.LOW)
	GPIO.output(led3, GPIO.LOW)
	for i in range(0,num):
		GPIO.output(led0, GPIO.HIGH)
		GPIO.output(led1, GPIO.HIGH)
		GPIO.output(led2, GPIO.HIGH)
		GPIO.output(led3, GPIO.HIGH)
		time.sleep(0.15)
		GPIO.output(led0, GPIO.LOW)
		GPIO.output(led1, GPIO.LOW)
		GPIO.output(led2, GPIO.LOW)
		GPIO.output(led3, GPIO.LOW)
		time.sleep(0.15)

# *------------*
# | Begin main |
# *------------*

print("\nDiscovering devices...", end="")
devices = pywemo.discover_devices()
print("Done!")

switch0 = devices[0]
switch1 = devices[1]
#switch2 = devices[2]
#switch3 = devices[3]

print("Button 0: ", switch0)
print("Button 1: ", switch1)
#print("Button 2: ", switch2)
#print("Button 3: ", switch3)

try:
	blink(2)
	time.sleep(0.5)
	print("Loop starting, ^C to quit")

	# Main loop
	while True:

	# Detect buttons
		if GPIO.input(but0) == GPIO.HIGH:
			trigger(but0, switch0)
		if GPIO.input(but1) == GPIO.HIGH:
			trigger(but1, switch1)
#		if GPIO.input(but2) == GPIO.HIGH:
#			trigger(but2, switch2)
#		if GPIO.input(but3) == GPIO.HIGH:
#			trigger(but3, switch3)

		# Get states
		state0 = switch0.get_state(True)
		state1 = switch1.get_state(True)
#		state2 = switch2.get_state(True)
#		state3 = switch3.get_state(True)

		# Light buttons
		if state0 == 0 and GPIO.input(led0) == GPIO.HIGH:
			print(devices[0], " toggled off")
			GPIO.output(led0, GPIO.LOW)
		elif state0 == 1 and GPIO.input(led0) == GPIO.LOW:
			print(devices[0], " toggled on")
			GPIO.output(led0, GPIO.HIGH)
		if state1 == 0 and GPIO.input(led1) == GPIO.HIGH:
			print(devices[1], " toggled off")
			GPIO.output(led1, GPIO.LOW)
		elif state1 == 1 and GPIO.input(led1) == GPIO.LOW:
			print(devices[1], " toggled on")
			GPIO.output(led1, GPIO.HIGH)
#		if state2 == 0 and GPIO.input(led2) == GPIO.HIGH:
#			print(devices[2], " toggled off")
#			GPIO.output(led2, GPIO.LOW)
#		elif state2 == 1 and GPIO.input(led2) == GPIO.LOW:
#			print(devices[2], " toggled on")
#			GPIO.output(led2, GPIO.HIGH)
#		if state3 == 0 and GPIO.input(led3) == GPIO.HIGH:
#			print(devices[3], " toggled off")
#			GPIO.output(led3, GPIO.LOW)
#		elif state3 == 1 and GPIO.input(led3) == GPIO.LOW:
#			print(devices[3], " toggled on")
#			GPIO.output(led3, GPIO.HIGH)

		# Wait for 1 millisecond
		time.sleep(0.001)

except KeyboardInterrupt:
	print("    Quit")
	GPIO.cleanup() # Reset GPIO settings
```

**Comment by sqldiablo** [comment]
If I had to guess, I'd say this is probably an environment variable/profile issue. Either the user that is running the script doesn't have the right path environment variable set to import python modules, or the environment variables aren't set yet or at all when running the script this way. You may need to import the module directly from a file path instead.

**Comment by ghost** [comment]
I've changed `import pywemo` to as follows:

```
import importlib.util
spec = importlib.util.spec_from_file_location("pywemo", "/home/pi/.local/lib/python3.7/site-packages/pywemo/__init__.py")
pywemo = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pywemo)
```

by following instructions at https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path. It runs fine when run as user still, but now the error I get at boot is:

```
Traceback (most recent call last):
	File "/home/pi/IFTTT/wemo2.py", line 1, in <module>
		spec.loader.exec_module(pywemo)
	File "<frozen importlib._bootstrap_external>", line 728, in exec_module
	File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
	File "/home/pi/.local/lib/python3.7/site-packages/pywemo/__init__.py", line 3, in <module>
		from .ouimeaux_device import Device as WeMoDevice # noqua F401
ModuleNotFoundError: No module named 'pywemo'
```

**Comment by sqldiablo** [comment]
Take a look at this, and see if it helps: https://raspberrypi.stackexchange.com/questions/78141/python-script-fails-with-importerror-when-run-from-rc-local

**Comment by ghost** [comment]
Running `sudo pip3 install pywemo` did it!
