### ISSUE TITLE
AttributeError while reading RulesDb table

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#276]
Originally reported here by @deftdawg: https://github.com/home-assistant/core/issues/52641#issuecomment-880552883

2021.7.1, I'm getting the following error which I suspect maybe related based on the relation to device rules and how the pywemo 0.6.5 fixes were relating in part to missing rules dbs and such:

```
Logger: homeassistant
Source: components/wemo/wemo_device.py:83
First occurred: 5:02:41 AM (13 occurrences)
Last logged: 5:27:48 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 210, in async_discover_and_schedule
    await self._wemo_dispatcher.async_add_unique_device(self._hass, device)
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 155, in async_add_unique_device
    device = await async_register_device(hass, self._config_entry, wemo)
  File "/usr/src/homeassistant/homeassistant/components/wemo/wemo_device.py", line 83, in async_register_device
    await hass.async_add_executor_job(wemo.ensure_long_press_virtual_device)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 151, in ensure_long_press_virtual_device
    self.add_long_press_udns([VIRTUAL_DEVICE_UDN])
  File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 105, in add_long_press_udns
    with rules_db_from_device(self) as rules_db:
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 390, in rules_db_from_device
    rules = RulesDb(
  File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 178, in __init__
    self._rule_devices = _index_by_primary_key(
  File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 437, in _index_by_primary_key
    result[row.primary_key_value()] = row
  File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/db_orm.py", line 98, in primary_key_value
    return getattr(self, self.primary_key_name())
AttributeError: 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
```

**Comment by deftdawg** [comment]
Don't know how to run this from hassio itself, so run from a Pi2 running octopi:

```
# pi@octopi:~ $ pip3 install pywemo
#  ... 
# pi@octopi:~ $ python3 wemo_dump.py
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
192.168.1.93 - Master Bedroom Blinds Power - Belkin Plugin Socket 1.0
        Firmware version: {'FirmwareVersion': 'FirmwareVersion:WeMo_WW_2.00.10966.PVT-OWRT-SNS|SkuNo:Plugin Device'}
192.168.1.69 - Pantelligent Hotplate - Belkin Plugin Socket 1.0
        Firmware version: {'FirmwareVersion': 'FirmwareVersion:WeMo_WW_2.00.10966.PVT-OWRT-SNS|SkuNo:Plugin Device'}
192.168.1.98 - Whole House Fan - Belkin Plugin Socket 1.0
        Firmware version: {'FirmwareVersion': 'FirmwareVersion:WeMo_WW_2.00.10966.PVT-OWRT-LS|SkuNo:Plugin Device'}
        GetRulesDBPath: {'RulesDBPath': 'http://192.168.1.98:49153/rules.db'}
        Rules: Unknown 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
        ensure_long_press_virtual_device: FAILED: 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
192.168.1.91 - Back Step Light - Belkin Plugin Socket 1.0
        Firmware version: {'FirmwareVersion': 'FirmwareVersion:WeMo_WW_2.00.10966.PVT-OWRT-LS|SkuNo:Plugin Device'}
        GetRulesDBPath: {'RulesDBPath': 'http://192.168.1.91:49153/rules.db'}
        Rules: Unknown 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
        ensure_long_press_virtual_device: FAILED: 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
192.168.1.145 - Basement Bath Fan - Belkin Plugin Socket 1.0
        Firmware version: {'FirmwareVersion': 'FirmwareVersion:WeMo_WW_2.00.10966.PVT-OWRT-LS|SkuNo:Plugin Device'}
        GetRulesDBPath: {'RulesDBPath': 'http://192.168.1.145:49153/rules.db'}
        Rules: Unknown 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
        ensure_long_press_virtual_device: FAILED: 'RuleDevicesRow' object has no attribute 'RuleDevicePK'
```

I haven't setup any long press rules on any of my wemos, attached are the `rules.db` for the devices that reported the missing attributes; each is prefixed by it's last ip octet.  

[rules.db.zip](https://github.com/pywemo/pywemo/files/6825754/rules.db.zip)

The 3 devices reporting that are all the old style wemo switches. 
<img src="https://www.belkin.com/resources/img/overview/f7c030/belkin-be-F7C030-01.jpg" width="15%">

**Comment by esev** [comment]
Thanks a lot for that @deftdawg. This is really helpful in understanding the failure. Here is the relevant parts of the rules.db file from `145`.

We see all of the expected tables within the database:
```
CREATE TABLE IF NOT EXISTS 'RULES'                      ('RuleID'PRIMARY KEY,                     'Name' TEXT NOT NULL,                     'Type' TEXT NOT NULL,                     'RuleOrder' INTEGER,                     'StartDate' TEXT,                     'EndDate' TEXT,                     'State' TEXT,                     'Sync' TEXT);
CREATE TABLE IF NOT EXISTS 'DEVICECOMBINATION'                     ('DeviceCombinationPK' INTEGER PRIMARY KEY AUTOINCREMENT,                     'RuleID' INTEGER,                     'SensorID' TEXT,                     'SensorGroupID' INTEGER,                     'DeviceID' TEXT,                     'DeviceGroupID' INTEGER);
CREATE TABLE IF NOT EXISTS 'SENSORNOTIFICATION'                     ('SensorNotificationPK' INTEGER PRIMARY KEY AUTOINCREMENT,                     'RuleID' INTEGER,                     'NotifyRuleID' INTEGER,                     'NotificationMessage' TEXT,                     'NotificationDuration' TEXT);
CREATE TABLE IF NOT EXISTS 'GROUPDEVICES'                     ('GroupDevicePK' INTEGER PRIMARY KEY AUTOINCREMENT,                     'GroupID' INTEGER,                     'DeviceID' TEXT);
CREATE TABLE IF NOT EXISTS 'LOCATIONINFO'                     ('LocationPk' INTEGER PRIMARY KEY AUTOINCREMENT,                     'cityName' TEXT,                     'countryName' TEXT,                     'latitude' TEXT,                     'longitude' TEXT,                     'countryCode' TEXT,                     'region' TEXT);
CREATE TABLE IF NOT EXISTS 'BLOCKEDRULES'                     ('Primarykey' INTEGER PRIMARY KEY AUTOINCREMENT,                     'ruleId' TEXT);
CREATE TABLE IF NOT EXISTS 'RULESNOTIFYMESSAGE' ('RuleID' INTEGER,'NotifyRuleID' TEXT NOT NULL,'Message' TEXT NOT NULL,'Frequency' INTEGER);
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE RULEDEVICES (RuleDevicePK UNIQUE, RuleID INTEGER, DeviceID, GroupID, DayID INTEGER, StartTime,RuleDuration, StartAction INTEGER, EndAction INTEGER, SensorDuration,Type,Value,Level,ZBCapabilityStart TEXT DEFAULT "", ZBCapabilityEnd TEXT  DEFAULT "", OnModeOffset INTEGER  DEFAULT 0,OffModeOffset INTEGER DEFAULT 0,CountdownTime INTEGER DEFAULT 0,EndTime INTEGER DEFAULT 0, ProductName TEXT  DEFAULT "");
CREATE TABLE TARGETDEVICES (TargetDevicesPK INTEGER PRIMARY KEY AUTOINCREMENT, RuleID INTEGER, DeviceID TEXT, DeviceIndex INTEGER);
```

But what was unexpected, and not properly handled in pyWeMo are the `NULL` values in the RULEDEVICES table entries. I'm not going to include them all, but here is an example of what pyWeMo was expecting...
```
INSERT INTO RULEDEVICES VALUES(288,11,'uuid:Lightswitch-1_0',0,7,60602,22138,1,0,300,-1,-1,-1,'','',0,0,0,0,'');
INSERT INTO RULEDEVICES VALUES(289,11,'uuid:Sensor-1_0',0,-1,60602,22138,-1,-1,-1,0,0,2,'0','0',0,0,0,0,'');
```

And here is what was unanticipated and caused pyWeMo to break.
```
INSERT INTO RULEDEVICES VALUES(NULL,22,'uuid:Lightswitch-1_0','0',1,'60','86280',0,0,'0','-1','-1','-1','-1','-1',0,0,1800,86340,'');
INSERT INTO RULEDEVICES VALUES(NULL,22,'uuid:Lightswitch-1_0','0',2,'60','86280',0,0,'0','-1','-1','-1','-1','-1',0,0,1800,86340,'');
```

This is really helpful as I now know that all the same tables are present in your devices' database, just some of the values in the table were not properly accounted for in pyWeMo.

I'm doing a fix in HA that will work around these pyWeMo database issues. This should get HA working again while I work on longer term fixes here in pyWeMo. Follow https://github.com/home-assistant/core/pull/53094 to know when the quick-fix gets merged.

**Comment by deftdawg** [comment]
Glad to be of help, thanks for doing what you do. 🍻
