### ISSUE TITLE
Error setting up entry Wemo for wemo - after 2021.7.2 update

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#277]
Originally reported here by @SCUZNUTS: https://github.com/home-assistant/core/issues/52996

> ### The problem
> Went from 2021.6.x to 2021.7.2 and noticed my wemo devices not functioning.
> 
> Log output is;
> 
> 2021-07-14 16:30:21 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wemo for wemo
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
> result = await component.async_setup_entry(hass, self) # type: ignore
> File "/usr/src/homeassistant/homeassistant/components/wemo/**init**.py", line 130, in async_setup_entry
> await wemo_discovery.discover_statics()
> File "/usr/src/homeassistant/homeassistant/components/wemo/**init**.py", line 246, in discover_statics
> await self._wemo_dispatcher.async_add_unique_device(
> File "/usr/src/homeassistant/homeassistant/components/wemo/**init**.py", line 155, in async_add_unique_device
> device = await async_register_device(hass, self._config_entry, wemo)
> File "/usr/src/homeassistant/homeassistant/components/wemo/wemo_device.py", line 83, in async_register_device
> await hass.async_add_executor_job(wemo.ensure_long_press_virtual_device)
> File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 151, in ensure_long_press_virtual_device
> self.add_long_press_udns([VIRTUAL_DEVICE_UDN])
> File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 105, in add_long_press_udns
> with rules_db_from_device(self) as rules_db:
> File "/usr/local/lib/python3.9/contextlib.py", line 117, in **enter**
> return next(self.gen)
> File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 390, in rules_db_from_device
> rules = RulesDb(
> File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 181, in **init**
> self._target_devices = _index_by_primary_key(
> File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 436, in _index_by_primary_key
> for row in rows:
> File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/db_orm.py", line 67, in select_all
> cursor.execute(f"SELECT {names} FROM {cls.TABLE_NAME}")
> sqlite3.OperationalError: no such table: TARGETDEVICES
> 
> I have also attempted to delete and readd the integration.
> Also attempted config yaml vs discovery.
> Also given the error I attempted renaming the home assistant DB and restarting.
> Same error each time.
> 
> ### What is version of Home Assistant Core has the issue?
> 2021.7.2
> 
> ### What was the last working version of Home Assistant Core?
> 2021.6.x
> 
> ### What type of installation are you running?
> Home Assistant OS
> 
> ### Integration causing the issue
> wemo
> 
> ### Link to integration documentation on our website
> https://www.home-assistant.io/integrations/wemo/
> 
> ### Example YAML snippet
> _No response_
> 
> ### Anything in the logs that might be useful for us?
> ```
> 2021-07-14 16:30:21 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wemo for wemo
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 130, in async_setup_entry
>     await wemo_discovery.discover_statics()
>   File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 246, in discover_statics
>     await self._wemo_dispatcher.async_add_unique_device(
>   File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 155, in async_add_unique_device
>     device = await async_register_device(hass, self._config_entry, wemo)
>   File "/usr/src/homeassistant/homeassistant/components/wemo/wemo_device.py", line 83, in async_register_device
>     await hass.async_add_executor_job(wemo.ensure_long_press_virtual_device)
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 151, in ensure_long_press_virtual_device
>     self.add_long_press_udns([VIRTUAL_DEVICE_UDN])
>   File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 105, in add_long_press_udns
>     with rules_db_from_device(self) as rules_db:
>   File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
>     return next(self.gen)
>   File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 390, in rules_db_from_device
>     rules = RulesDb(
>   File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 181, in __init__
>     self._target_devices = _index_by_primary_key(
>   File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 436, in _index_by_primary_key
>     for row in rows:
>   File "/usr/local/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/db_orm.py", line 67, in select_all
>     cursor.execute(f"SELECT {names} FROM {cls.TABLE_NAME}")
> sqlite3.OperationalError: no such table: TARGETDEVICES
> ```
> 
> ### Additional information
> _No response_

rules.db file was attached in https://github.com/home-assistant/core/issues/52996#issuecomment-879608436

Decoded rules: https://github.com/home-assistant/core/issues/52996#issuecomment-879617955

> Thank you. I see the issue. Here is the decoded rules.db file that you attached.
> 
> ```
> $ unzip rules.db
> Archive:  rules.db
>   inflating: temppluginRules.db      
> $ sqlite3 temppluginRules.db 
> SQLite version 3.22.0 2018-01-22 18:45:57
> Enter ".help" for usage hints.
> sqlite> .dump
> PRAGMA foreign_keys=OFF;
> BEGIN TRANSACTION;
> CREATE TABLE IF NOT EXISTS 'RULES'                      ('RuleID'PRIMARY KEY,                     'Name' TEXT NOT NULL,                     'Type' TEXT NOT NULL,                     'RuleOrder' INTEGER,                     'StartDate' TEXT,                     'EndDate' TEXT,                     'State' TEXT,                     'Sync' TEXT);
> CREATE TABLE IF NOT EXISTS 'DEVICECOMBINATION'                     ('DeviceCombinationPK' INTEGER PRIMARY KEY AUTOINCREMENT,                     'RuleID' INTEGER,                     'SensorID' TEXT,                     'SensorGroupID' INTEGER,                     'DeviceID' TEXT,                     'DeviceGroupID' INTEGER);
> CREATE TABLE IF NOT EXISTS 'SENSORNOTIFICATION'                     ('SensorNotificationPK' INTEGER PRIMARY KEY AUTOINCREMENT,                     'RuleID' INTEGER,                     'NotifyRuleID' INTEGER,                     'NotificationMessage' TEXT,                     'NotificationDuration' TEXT);
> CREATE TABLE IF NOT EXISTS 'GROUPDEVICES'                     ('GroupDevicePK' INTEGER PRIMARY KEY AUTOINCREMENT,                     'GroupID' INTEGER,                     'DeviceID' TEXT);
> CREATE TABLE IF NOT EXISTS 'LOCATIONINFO'                     ('LocationPk' INTEGER PRIMARY KEY AUTOINCREMENT,                     'cityName' TEXT,                     'countryName' TEXT,                     'latitude' TEXT,                     'longitude' TEXT,                     'countryCode' TEXT,                     'region' TEXT);
> CREATE TABLE IF NOT EXISTS 'BLOCKEDRULES'                     ('Primarykey' INTEGER PRIMARY KEY AUTOINCREMENT,                     'ruleId' TEXT);
> CREATE TABLE IF NOT EXISTS 'RULESNOTIFYMESSAGE' ('RuleID' INTEGER,'NotifyRuleID' TEXT NOT NULL,'Message' TEXT NOT NULL,'Frequency' INTEGER);
> CREATE TABLE android_metadata (locale TEXT);
> INSERT INTO android_metadata VALUES('en_NZ');
> CREATE TABLE RULEDEVICES (RuleDevicePK UNIQUE, RuleID INTEGER, DeviceID, GroupID, DayID INTEGER, StartTime,RuleDuration, StartAction INTEGER, EndAction INTEGER, SensorDuration,Type,Value,Level,ZBCapabilityStart TEXT DEFAULT "", ZBCapabilityEnd TEXT  DEFAULT "", OnModeOffset INTEGER  DEFAULT 0,OffModeOffset INTEGER DEFAULT 0,CountdownTime INTEGER DEFAULT 0,EndTime INTEGER DEFAULT 0, ProductName TEXT  DEFAULT "");
> DELETE FROM sqlite_sequence;
> INSERT INTO sqlite_sequence VALUES('LOCATIONINFO',1);
> COMMIT;
> sqlite> 
> ```
> 
> It looks like, for some reason, it doesn't have the `CREATE TABLE TARGETDEVICES(TargetDevicesPK INTEGER PRIMARY KEY AUTOINCREMENT, RuleID INTEGER, DeviceID TEXT, DeviceIndex INTEGER);` part that other device has (and that the devices I've tested on have).
> 
> I can fix this in the pyWeMo code. It should handle the case where the expected tables do not exist. At the very least pyWeMo shouldn't be breaking the Wemo HA component. It might take a few days for me to get to the fix, but I'll try to have it complete by the end of the weekend.

**Comment by Spectre5** [comment]
Was this fixed - or still only the temporary fix?

**Comment by esev** [comment]
Still just a temporary fix.

**Comment by esev** [comment]
I still plan to fix it. But I'm waiting for https://github.com/home-assistant/core/pull/56972 first, so there is an easy way for folks to disable it if there are further breakages.

**Comment by TaylorTWBrown** [comment]
Hey folks, looks like the above changes have been merged. Is this issue resolved, or are there still outstanding problems that need to be fixed? I'm troubleshooting this issue in my HASS instance.

**Comment by esev** [comment]
@TaylorTWBrown You're seeing the `sqlite3.OperationalError: no such table: TARGETDEVICES` error in Home Assistant?

That should have been fixed long ago. Did it start happening again?

**Comment by esev** [comment]
Does the log start with `Unable to add WeMo`?

**Comment by TaylorTWBrown** [comment]
Correct, here's a snippet from my log.

`pywemo.exceptions.RulesDbQueryError: sqlite3 exception no such table: TARGETDEVICES
2023-08-01 00:29:53.434 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 389, in rules_db_from_device
    rules = RulesDb(
            ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 182, in __init__
    self._target_devices = _index_by_primary_key(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 446, in _index_by_primary_key
    for row in rows:
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/db_orm.py", line 65, in select_all
    cursor.execute(f"SELECT {names} FROM {cls.TABLE_NAME}")`

I just updated a neglected home assistant instance, so I'm still troubleshooting.

**Comment by esev** [comment]
What version of HA are you using? Are you running the 2023.8.0 beta?

**Comment by TaylorTWBrown** [comment]
I just upgraded to 2023.7.3 directly from 2023.3.5.

Let me know if I can provide more detailed information/context.

My version:

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Here's a more complete log snippet.

`
Logger: homeassistant.config_entries
Source: components/wemo/wemo_device.py:142
First occurred: 12:29:17 AM (1 occurrences)
Last logged: 12:29:17 AM

Error setting up entry Wemo for wemo
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 389, in rules_db_from_device
    rules = RulesDb(
            ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 182, in __init__
    self._target_devices = _index_by_primary_key(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 446, in _index_by_primary_key
    for row in rows:
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/db_orm.py", line 65, in select_all
    cursor.execute(f"SELECT {names} FROM {cls.TABLE_NAME}")
sqlite3.OperationalError: no such table: TARGETDEVICES

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 132, in async_setup_entry
    await wemo_discovery.async_discover_and_schedule()
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 229, in async_discover_and_schedule
    await self._wemo_dispatcher.async_add_unique_device(self._hass, device)
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 161, in async_add_unique_device
    coordinator = await async_register_device(hass, self._config_entry, wemo)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wemo/wemo_device.py", line 266, in async_register_device
    await device.async_set_options(hass, config_entry)
  File "/usr/src/homeassistant/homeassistant/components/wemo/wemo_device.py", line 167, in async_set_options
    await getattr(self, f"_async_set_{field.name}")(new_value)
  File "/usr/src/homeassistant/homeassistant/components/wemo/wemo_device.py", line 142, in _async_set_enable_long_press
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 164, in ensure_long_press_virtual_device
    self.add_long_press_udns([VIRTUAL_DEVICE_UDN])
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/long_press.py", line 115, in add_long_press_udns
    with rules_db_from_device(self) as rules_db:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywemo/ouimeaux_device/api/rules_db.py", line 403, in rules_db_from_device
    raise RulesDbQueryError(f"sqlite3 exception {err}") from err
pywemo.exceptions.RulesDbQueryError: sqlite3 exception no such table: TARGETDEVICES
`

**Comment by esev** [comment]
Thanks for this! Looks like I broke things in https://github.com/home-assistant/core/pull/56972. Let me get that right tonight and hopefully it can make the 2023.8.0 release.

Here is a temporary solution for you. Go into Settings -> Devices & Services and click on the Belkin WeMo integration. Then click Configure and uncheck `Register for device long-press events`. That should resolve the issue for you. But please let me know if it is still broken.

**Comment by TaylorTWBrown** [comment]
Thanks Eric, unchecking 'Register for device long-press events' and restarting HASS has helped for now. I'll watch this thread and I'm happy to beta-test any updates you prepare.

**Comment by esev** [comment]
I think the only change needed will be the one line change in #522. That will get things back to the state they were for you in 2023.3.5.

I still need to implement support for the long press feature for this device (which is why I had left this bug open). But at least these switches/dimmers will work in HASS again. 🤦

**Comment by esev** [comment]
This fix made it into the [2023.8.0 beta](https://github.com/home-assistant/core/releases/tag/2023.8.0b3), so it should be fixed in the 2023.8.0 release later this week too.

This just stops the devices from being broken in Home Assistant. It doesn't implement the long press feature for this device.

If that feature is important, let me know, I can spend some time working on this feature.

**Comment by TaylorTWBrown** [comment]
Long press on the original Wemo switches is certainly something I'd appreciate. However, these are super old devices so I'm not expecting any miracles.

If it helps, I have some of the original Wemo switches new in box that I can donate/mail to you. I stocked up when they went on sale for ~$25 CAD and have some extras.

**Comment by esev** [comment]
> Long press on the original Wemo switches is certainly something I'd appreciate.

Perfect. I was looking for a reason to work on this :)

> If it helps, I have some of the original Wemo switches new in box that I can donate/mail to you.

I think I have some data already from these older devices. Let me see if I can make progress with that data.

Are you able to download a branch from GitHub and do some testing when I have a change ready?

**Comment by TaylorTWBrown** [comment]
Yeah, I can definitely test any changes you're working on! Let me know.
