### ISSUE TITLE
Issues detecting Wemo devices

### ISSUE THREAD

**Issue by emilic14** [pywemo/pywemo#292]
Hello, I've been struggling for the last few days trying to get my Wemo devices detected/installed in home assistant...
So I've been playing around trying to figure it out and now I give up and am I looking for help in the community ^^ because I think I have a bug here...

Running pywemo 0.6.7

when trying  "devices = pywemo.discover_devices()"
I get : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywemo/discovery.py", line 37, in discover_devices
    device = device_from_uuid_and_location(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywemo/discovery.py", line 87, in device_from_uuid_and_location
    return Bridge(location)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywemo/ouimeaux_device/bridge.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywemo/ouimeaux_device/__init__.py", line 115, in __init__
    self._config_any = {
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywemo/ouimeaux_device/__init__.py", line 115, in <dictcomp>
    self._config_any = {
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywemo/ouimeaux_device/__init__.py", line 114, in <genexpr>
    xs_any = (et.fromstring(extra) for extra in self._config.anytypeobjs_)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 2
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 2, column 1
```

I've tried resetting my Wemo devices (tested with 3 different wemo devices, all at the same time and one by one), making sure that there are no rules... even changing my wemo account to a clean one ^^
And nothing.

Any ideas of what is going on?

**Comment by emilic14** [comment]
for info, my setup of one of my wemo is as follows  :

```
cat setup.xml
<?xml version="1.0"?>
<root xmlns="urn:Belkin:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
<deviceType>urn:Belkin:device:insight:1</deviceType>
<friendlyName>Wemo Insight</friendlyName>
    <manufacturer>Belkin International Inc.</manufacturer>
    <manufacturerURL>http://www.belkin.com</manufacturerURL>
    <modelDescription>Belkin Insight 1.0</modelDescription>
    <modelName>Insight</modelName>
    <modelNumber>1.0</modelNumber>
    <modelURL>http://www.belkin.com/plugin/</modelURL>
<serialNumber>XXXXXXXX</serialNumber>
<UDN>uuid:Insight-1_0-XXXXXXXX</UDN>
    <UPC>XXXXXX</UPC>
<macAddress>XXXXXXXX</macAddress>
<firmwareVersion>WeMo_WW_2.00.11532.PVT-OWRT-Insight</firmwareVersion>
<iconVersion>0|49153</iconVersion>
<binaryState>0</binaryState>
    <binaryOption>1</binaryOption>
    <new_algo>1</new_algo>
    <iconList>
      <icon>
        <mimetype>jpg</mimetype>
        <width>100</width>
        <height>100</height>
        <depth>100</depth>
         <url>icon.jpg</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
        <serviceType>urn:Belkin:service:WiFiSetup:1</serviceType>
        <serviceId>urn:Belkin:serviceId:WiFiSetup1</serviceId>
        <controlURL>/upnp/control/WiFiSetup1</controlURL>
        <eventSubURL>/upnp/event/WiFiSetup1</eventSubURL>
        <SCPDURL>/setupservice.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:Belkin:service:timesync:1</serviceType>
        <serviceId>urn:Belkin:serviceId:timesync1</serviceId>
        <controlURL>/upnp/control/timesync1</controlURL>
        <eventSubURL>/upnp/event/timesync1</eventSubURL>
        <SCPDURL>/timesyncservice.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:Belkin:service:basicevent:1</serviceType>
        <serviceId>urn:Belkin:serviceId:basicevent1</serviceId>
        <controlURL>/upnp/control/basicevent1</controlURL>
        <eventSubURL>/upnp/event/basicevent1</eventSubURL>
        <SCPDURL>/eventservice.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:Belkin:service:firmwareupdate:1</serviceType>
        <serviceId>urn:Belkin:serviceId:firmwareupdate1</serviceId>
        <controlURL>/upnp/control/firmwareupdate1</controlURL>
        <eventSubURL>/upnp/event/firmwareupdate1</eventSubURL>
        <SCPDURL>/firmwareupdate.xml</SCPDURL>
      </service>
      <service>
        <serviceType>urn:Belkin:service:rules:1</serviceType>
        <serviceId>urn:Belkin:serviceId:rules1</serviceId>
        <controlURL>/upnp/control/rules1</controlURL>
        <eventSubURL>/upnp/event/rules1</eventSubURL>
        <SCPDURL>/rulesservice.xml</SCPDURL>
      </service>

      <service>
        <serviceType>urn:Belkin:service:metainfo:1</serviceType>
        <serviceId>urn:Belkin:serviceId:metainfo1</serviceId>
        <controlURL>/upnp/control/metainfo1</controlURL>
        <eventSubURL>/upnp/event/metainfo1</eventSubURL>
        <SCPDURL>/metainfoservice.xml</SCPDURL>
      </service>

      <service>
        <serviceType>urn:Belkin:service:remoteaccess:1</serviceType>
        <serviceId>urn:Belkin:serviceId:remoteaccess1</serviceId>
        <controlURL>/upnp/control/remoteaccess1</controlURL>
        <eventSubURL>/upnp/event/remoteaccess1</eventSubURL>
        <SCPDURL>/remoteaccess.xml</SCPDURL>
      </service>

      <service>
        <serviceType>urn:Belkin:service:deviceinfo:1</serviceType>
        <serviceId>urn:Belkin:serviceId:deviceinfo1</serviceId>
        <controlURL>/upnp/control/deviceinfo1</controlURL>
        <eventSubURL>/upnp/event/deviceinfo1</eventSubURL>
        <SCPDURL>/deviceinfoservice.xml</SCPDURL>
      </service>

      <service>
        <serviceType>urn:Belkin:service:insight:1</serviceType>
        <serviceId>urn:Belkin:serviceId:insight1</serviceId>
        <controlURL>/upnp/control/insight1</controlURL>
        <eventSubURL>/upnp/event/insight1</eventSubURL>
        <SCPDURL>/insightservice.xml</SCPDURL>
      </service>

      <service>
        <serviceType>urn:Belkin:service:smartsetup:1</serviceType>
        <serviceId>urn:Belkin:serviceId:smartsetup1</serviceId>
        <controlURL>/upnp/control/smartsetup1</controlURL>
        <eventSubURL>/upnp/event/smartsetup1</eventSubURL>
        <SCPDURL>/smartsetup.xml</SCPDURL>
      </service>

      <service>
        <serviceType>urn:Belkin:service:manufacture:1</serviceType>
        <serviceId>urn:Belkin:serviceId:manufacture1</serviceId>
        <controlURL>/upnp/control/manufacture1</controlURL>
        <eventSubURL>/upnp/event/manufacture1</eventSubURL>
        <SCPDURL>/manufacture.xml</SCPDURL>
      </service>

    </serviceList>
   <presentationURL>/pluginpres.html</presentationURL>
</device>
</root>
```

**Comment by esev** [comment]
Hi @emilic14,

I may have seen this (or something similar) before. https://github.com/home-assistant/core/issues/53850

Is it possible you have version of libxml2 that is incompatible with the lxml package?
https://bugs.launchpad.net/lxml/+bug/1928795

```python
from lxml import etree
print(etree.LIBXML_VERSION)
```

**Comment by emilic14** [comment]
Thank you!

So i've got : 

```
>>> from lxml import etree
>>> print(etree.LIBXML_VERSION)
(2, 9, 12)
```

Seems that v 2.9.10 is not available for Termux, doing a request there...

**Comment by esev** [comment]
You're welcome. If it helps, I added a simple test case in https://github.com/linuxserver/docker-homeassistant/issues/17. That can be used by the Termux folks to verify the fix.

**Comment by Spectre5** [comment]
Is this still an issue @emilic14 or has a newer version of lxml fixed it?

**Comment by emilic14** [comment]
> Is this still an issue @emilic14 or has a newer version of lxml fixed it?

Hello, Sorry as it was not working when I was needing it I changed how I was handling my project without requiring lxml or termux to bypass the issue.
So I cant really answer your question.
