### ISSUE TITLE
Unable to connect my insightV2 Smart Plug to my WI-Fi Network

### ISSUE THREAD

**Issue by xraive** [pywemo/pywemo#357]
I'm having issues connecting my insightV2 plug to my Wi-Fi Network.  I'm including some helpful info below.

Model: F7C029V2
Firmware:  WeMo_WW_2.00.10062.PVT-OWRT-InsightV2

### **Result of device.explain()**

```
>>> device.explain()

WiFiSetup`
---------
  GetApList() -> ApList
  GetNetworkList() -> NetworkList
  ConnectHomeNetwork(ssid, auth, password, encrypt, channel)
  GetNetworkStatus() -> NetworkStatus
  CloseSetup()
  StopPair()

timesync
--------
  TimeSync(UTC, TimeZone, dst, DstSupported)
  GetTime()

basicevent
----------
  SetBinaryState(BinaryState, Duration, EndAction, UDN) -> (CountdownEndTime, deviceCurrentTime)
  UpdateInsightHomeSettings(EnergyPerUnitCost, Currency, EnergyPerUnitCostVersion)
  SetInsightHomeSettings(EnergyPerUnitCost, Currency)
  GetInsightHomeSettings() -> (HomeSettingsVersion, EnergyPerUnitCost, Currency)
  SetLogLevelOption(Level, Option)
  GetFriendlyName(FriendlyName)
  ReSetup(Reset)
  SetHomeId(HomeId)
  GetHomeId()
  GetHomeInfo()
  SetDeviceId(SetDeviceId)
  GetDeviceId()
  GetMacAddr()
  GetSerialNo()
  GetPluginUDN()
  GetSmartDevInfo()
  ShareHWInfo(Mac, Serial, Udn, RestoreState, HomeId, PluginKey)
  ChangeFriendlyName(FriendlyName)
  SetSmartDevInfo(SmartDevURL)
  GetRuleOverrideStatus(RuleOverrideStatus)
  GetDeviceIcon(DeviceIcon)
  GetIconURL() -> URL
  GetLogFileURL() -> LOGURL
  ChangeDeviceIcon(PictureSize, PictureHeight, PictureColorDeep)
  GetBinaryState() -> BinaryState
  SetMultiState(state, state, state)
  SetCrockpotState(mode, time)
  GetCrockpotState() -> (mode, time)
  GetWatchdogFile() -> WDFile
  GetSignalStrength(SignalStrength)
  SetServerEnvironment(ServerEnvironment, TurnServerEnvironment, ServerEnvironmentType)
  GetServerEnvironment() -> (ServerEnvironment, TurnServerEnvironment, ServerEnvironmentType)
  GetIconVersion() -> IconVersion
  GetSimulatedRuleData()
  NotifyManualToggle()
  ControlCloudUpload(EnableUpload)

firmwareupdate
--------------
  UpdateFirmware(NewFirmwareVersion, ReleaseDate, URL, Signature, DownloadStartTime, WithUnsignedImage)
  GetFirmwareVersion() -> FirmwareVersion

rules
-----
  UpdateWeeklyCalendar(Mon, Tues, Wed, Thurs, Fri, Sat, Sun)
  EditWeeklycalendar(action)
  GetRulesDBPath() -> RulesDBPath
  SetRulesDBVersion(RulesDBVersion)
  GetRulesDBVersion() -> RulesDBVersion
  SetRuleID(RuleID, RuleMsg, RuleFreq)
  DeleteRuleID(RuleID)
  SimulatedRuleData(DeviceList, DeviceCount)
  FetchRules() -> (ruleDbPath, ruleDbVersion, errorInfo)
  StoreRules(ruleDbVersion, processDb, ruleDbBody) -> errorInfo

metainfo
--------
  GetMetaInfo() -> MetaInfo
  GetExtMetaInfo() -> ExtMetaInfo

remoteaccess
------------
  RemoteAccess(DeviceId, dst, HomeId, DeviceName, MacAddr, pluginprivateKey, smartprivateKey, smartUniqueId, numSmartDev) -> ArpMac

deviceinfo
----------
  GetDeviceInformation(UTC, TimeZone, dst, DstSupported) -> (DeviceInformation, CountdownTime, TimeSync)
  GetInformation(UTC, TimeZone, dst, DstSupported) -> (Information, TimeSync)
  OpenInstaAP()
  CloseInstaAP()
  GetConfigureState() -> ConfigureState
  InstaConnectHomeNetwork(ssid, auth, password, encrypt, channel, brlist)
  UpdateBridgeList(BridgeList)
  GetRouterInformation() -> (mac, ssid, auth, password, encrypt, channel)
  InstaRemoteAccess(DeviceId, dst, HomeId, DeviceName, MacAddr, pluginprivateKey, smartprivateKey, smartUniqueId, numSmartDev)

insight
-------
  GetPower() -> InstantPower
  GetTodayKWH() -> TodayKWH
  SetAutoPowerThreshold(PowerThreshold)
  GetPowerThreshold() -> PowerThreshold
  SetPowerThreshold(PowerThreshold)
  ResetPowerThreshold(PowerThreshold)
  GetInsightInfo() -> InsightInfo
  GetInsightParams() -> InsightParams
  GetONFor() -> ONFor
  GetInSBYSince() -> InSBYSince
  GetTodayONTime() -> TodayONTime
  GetTodaySBYTime() -> TodaySBYTime
  ScheduleDataExport(EmailAddress, DataExportType)
  GetDataExportInfo() -> (LastDataExportTS, DataExportType, EmailAddress)

smartsetup
----------
  PairAndRegister(PairingData, RegistrationData) -> PairingStatus
  GetRegistrationData(SmartDeviceData) -> RegistrationData
  GetRegistrationStatus() -> (RegistrationStatus, StatusCode)

manufacture
-----------
  GetManufactureData() -> ManufactureData
```

### **Result of when I try to connect to my Wi-Fi Network.**

```
>>> device.setup(ssid="test wifi", password="password123")
INFO:pywemo.ouimeaux_device:scanning for AP's...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 441
DEBUG:pywemo.ouimeaux_device:found AP: test wifi|1|100|WPA2PSK/AES
INFO:pywemo.ouimeaux_device:selecting AP: test wifi|1|100|WPA2PSK/AES
DEBUG:pywemo.ouimeaux_device:AP channel: 1
DEBUG:pywemo.ouimeaux_device:AP authorization mode(s): WPA2PSK
DEBUG:pywemo.ouimeaux_device:AP encryption method: AES
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/metainfo1 HTTP/1.1" 200 374
DEBUG:pywemo.ouimeaux_device:password length (before encryption): 18
DEBUG:pywemo.ouimeaux_device:password length (after encryption): 24
INFO:pywemo.ouimeaux_device:sending connection request (try 1)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 305
DEBUG:pywemo.ouimeaux_device:pairing status (send 1): Connecting
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 305
DEBUG:pywemo.ouimeaux_device:pairing status (send 2): Connecting
INFO:pywemo.ouimeaux_device:starting status checks (15.0 second timeout)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:initial status check: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 1.42 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 2.45 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 3.50 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 4.53 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 5.57 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 6.61 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 7.64 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 8.68 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 9.73 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 10.77 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 11.81 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 12.83 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 13.88 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 14.92 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:network status after 15.96 seconds: 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 272
DEBUG:pywemo.ouimeaux_device:network status: 0
DEBUG:pywemo.ouimeaux_device:close status: success
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\__init__.py", line 450, in setup
    return self._setup(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\__init__.py", line 668, in _setup
    raise SetupException(
pywemo.exceptions.SetupException: Wemo device failed to connect to "test wifi".  It could be a wrong password or Wemo device/firmware issue.  Please try again.
>>>
```

Any help would be greatly appreciated.  Let me if you need additional information.

**Comment by Spectre5** [comment]
I'm sure you're already tried running this several times with the same result?

I've seen this when the wifi connection for the device was not very good, so I'd recommend getting the WeMo device as close as possible to the wireless access point during setup, if possible.  In my limited experiences with WeMo, they seem to need a better connection during that initial setup for some reason.

If you can't get closer, another idea is to increase the timeout on the  `setup` function to 30 or 60 seconds and maybe increase the `connection_attempts`.

If both of those fail, you might try editing [this line](https://github.com/pywemo/pywemo/blob/c34e74629a67d74b9dbdf2490d70df215989b0bf/pywemo/ouimeaux_device/__init__.py#L561), maybe changing `range(2)` to `range(1)` or `range(3)`.

If you get it working, please report back what works!

**Comment by xraive** [comment]
Thank you for responding to my issue.  I just wanted to let you that I tried your suggestions and I still receieved the same errors.  My insightv2 plug is about 10 feet away from my AP in the same room.  

However I did create a non-secure SSID just for testing and I was successfully able to connect the device.  See the result of the connection attempt below.

```
>>> device.setup(ssid='testap', password=None)
INFO:pywemo.ouimeaux_device:scanning for AP's...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 551
DEBUG:pywemo.ouimeaux_device:found AP: testwifi|1|100|WPA2PSK/AES
DEBUG:pywemo.ouimeaux_device:found AP: testap|1|100|OPEN/NONE
INFO:pywemo.ouimeaux_device:selecting AP: testap|1|100|OPEN/NONE
DEBUG:pywemo.ouimeaux_device:AP channel: 1
DEBUG:pywemo.ouimeaux_device:AP authorization mode(s): OPEN
DEBUG:pywemo.ouimeaux_device:AP encryption method: NONE
DEBUG:pywemo.ouimeaux_device:selected network has no encryption (password ignored)
DEBUG:pywemo.ouimeaux_device:password length (after encryption):
DEBUG:pywemo.ouimeaux_device:password length (after encryption):
INFO:pywemo.ouimeaux_device:sending connection request (try 1)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 305
DEBUG:pywemo.ouimeaux_device:pairing status (send 1): Connecting
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 305
DEBUG:pywemo.ouimeaux_device:pairing status (send 2): Connecting
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 305
DEBUG:pywemo.ouimeaux_device:pairing status (send 3): Connecting
INFO:pywemo.ouimeaux_device:starting status checks (30.0 second timeout)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 292
DEBUG:pywemo.ouimeaux_device:initial status check: 1
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 272
DEBUG:pywemo.ouimeaux_device:network status: 1
DEBUG:pywemo.ouimeaux_device:close status: success
DEBUG:pywemo.ouimeaux_device:SetSetupDoneStatus not available (some devices do not have this method)
INFO:pywemo.ouimeaux_device:Wemo device connected to "testap" in 0.59 seconds (1 connection attempts(s))
('1', 'success')
```

It looks to be an issue witht the password.  My other devices all connect to the test network fine using a password that is 18 characters long consisting of only letters and numbers.   Perhaps the encryption might be an issue.  Unfotunately I'm not familiar with it enough to make any changes.

Any suggestions would be greatly appreciated.

**Comment by Spectre5** [comment]
Ah.  Ok, this is one that @esev may be able to better help with.  He found that some newer devices running RTOS salt the password differently.  The RTOS devices should be automatically detected though.  What is the output of `device._config_any.get('rtos', '0')`, or even more generally `device._config_any` to see the entire dictionary ([see here](https://github.com/pywemo/pywemo/blob/c34e74629a67d74b9dbdf2490d70df215989b0bf/pywemo/ouimeaux_device/__init__.py#L540)).  How new is this device and do you know what firmware version the WeMo device has?

It could be possible that they've changed how the salting works...

**Comment by xraive** [comment]
Hi, I don't think it's a new device.  I don't know if you missed it :smiley:  but I had my firmware version on the OP.  I'm including it below as well.

Model: F7C029V2
Firmware: WeMo_WW_2.00.10062.PVT-OWRT-InsightV2

It doesn't look to be RTOS as it mentions OWRT in the firmware version but I might be mistaken.

I"m including the output of both commands you mentioned below just in case.

**>>> device._config_any.get('rtos', '0')**
'0'

**>>> device._config_any**
{'firmwareVersion': 'WeMo_WW_2.00.10062.PVT-OWRT-InsightV2', 'iconVersion': '0|49152', 'binaryState': '0'}

Again thanks for looking into this.

**Comment by Spectre5** [comment]
Ah, I did miss that.  Let's see if @esev has any inputs - my best guess/assumption is that something in the salting has changed with the password, so perhaps he can try doing again what he did for the RTOS work.

**Comment by esev** [comment]
I have one of these InsightV2 devices. I'll try changing the pyWeMo code a bit to see if the RTOS logic is what is needed on these too. I can't do it today, but will report back later in the week if that works.

**Comment by xraive** [comment]
My apologies for the delay, thank you for looking into this.  It's a great device and hopefully it can be supported. 
Much appreciated.

**Comment by xraive** [comment]
@esev Just following up to see if you had a chance to look into getting support for this device. 😃

**Comment by esev** [comment]
I gave this a try today. This doesn't work with the RTOS logic either.

**Comment by esev** [comment]
@xraive do you have any devices that work correctly with the wifi setup?

**Comment by esev** [comment]
@xraive would you be able to test the change to `pywemo/ouimeaux_device/__init__.py` in https://github.com/pywemo/pywemo/pull/360?

Basically the change is to this line:
```python
encrypted_password = base64.b64encode(openssl.stdout[16:]).decode()
```

Change it to this and see if that solves the issue for you:
```python
encrypted_password = base64.b64encode(openssl.stdout).decode()
```

**Comment by xraive** [comment]
@esev great news the change you suggested helped in connecting the WeMo Insight V2 switch to my Wi-Fi network successfully.   I did get an error message during the process but the device did successfully connect.  

It also resolved #358 for me, as I was able to connect the Wemo Smart Switch (F7C027) successfully without any errors.


Please see the log below with the error messaged I received when trying to conect my WeMo Insight device?

```
>>> import logging
>>> import pywemo
>>> logging.basicConfig(level=logging.DEBUG)
>>> devices = pywemo.discover_devices()
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /setup.xml HTTP/1.1" 200 4758
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /setupservice.xml HTTP/1.1" 200 3278
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /timesyncservice.xml HTTP/1.1" 200 1718
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /eventservice.xml HTTP/1.1" 200 20836
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /firmwareupdate.xml HTTP/1.1" 200 1826
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /rulesservice.xml HTTP/1.1" 200 9668
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /metainfoservice.xml HTTP/1.1" 200 1132
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /remoteaccess.xml HTTP/1.1" 200 3974
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /deviceinfoservice.xml HTTP/1.1" 200 9922
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /insightservice.xml HTTP/1.1" 200 6336
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /smartsetup.xml HTTP/1.1" 200 2536
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /manufacture.xml HTTP/1.1" 200 642
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/insight1 HTTP/1.1" 200 321
>>> print(devices)
[<WeMo Insight "WeMo Insight">]
>>> devices[0].toggle()
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/insight1 HTTP/1.1" 200 321
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/basicevent1 HTTP/1.1" 200 285
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/basicevent1 HTTP/1.1" 200 393
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/insight1 HTTP/1.1" 200 321
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/basicevent1 HTTP/1.1" 200 285
>>> devices[0].setup(ssid='test', password='password123')
INFO:pywemo.ouimeaux_device:scanning for AP's...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 402
DEBUG:pywemo.ouimeaux_device:found AP: test|1|100|WPA2PSK/AES
INFO:pywemo.ouimeaux_device:selecting AP: test|1|100|WPA2PSK/AES
DEBUG:pywemo.ouimeaux_device:AP channel: 1
DEBUG:pywemo.ouimeaux_device:AP authorization mode(s): WPA2PSK
DEBUG:pywemo.ouimeaux_device:AP encryption method: AES
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/metainfo1 HTTP/1.1" 200 374
DEBUG:pywemo.ouimeaux_device:password length (before encryption): 13
DEBUG:pywemo.ouimeaux_device:password length (after encryption): 24
INFO:pywemo.ouimeaux_device:sending connection request (try 1)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 200 305
DEBUG:pywemo.ouimeaux_device:pairing status (send 1): Connecting
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 500 411
WARNING:pywemo.ouimeaux_device.api.service:Error communicating with WeMo Insight at 10.22.22.1:49152, HTTPNotOkException('Received status 500 for http://10.22.22.1:49152/upnp/control/WiFiSetup1') retry 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /setup.xml HTTP/1.1" 200 4758
INFO:pywemo.ouimeaux_device:Reconnected to wemo <WeMo Insight "WeMo Insight"> on port 49152
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 500 411
WARNING:pywemo.ouimeaux_device.api.service:Error communicating with WeMo Insight at 10.22.22.1:49152, HTTPNotOkException('Received status 500 for http://10.22.22.1:49152/upnp/control/WiFiSetup1') retry 1
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /setup.xml HTTP/1.1" 200 4758
INFO:pywemo.ouimeaux_device:Reconnected to wemo <WeMo Insight "WeMo Insight"> on port 49152
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "POST /upnp/control/WiFiSetup1 HTTP/1.1" 500 411
WARNING:pywemo.ouimeaux_device.api.service:Error communicating with WeMo Insight at 10.22.22.1:49152, HTTPNotOkException('Received status 500 for http://10.22.22.1:49152/upnp/control/WiFiSetup1') retry 2
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.22.22.1:49152
DEBUG:urllib3.connectionpool:http://10.22.22.1:49152 "GET /setup.xml HTTP/1.1" 200 4758
INFO:pywemo.ouimeaux_device:Reconnected to wemo <WeMo Insight "WeMo Insight"> on port 49152
ERROR:pywemo.ouimeaux_device.api.service:Error communicating with WeMo Insight after 3 attempts. Giving up.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\api\service.py", line 227, in __call__
    response = session.post(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\api\service.py", line 142, in post
    return self.request('POST', url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\api\service.py", line 128, in request
    raise HTTPNotOkException(
pywemo.exceptions.HTTPNotOkException: Received status 500 for http://10.22.22.1:49152/upnp/control/WiFiSetup1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\__init__.py", line 451, in setup
    return self._setup(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\__init__.py", line 563, in _setup
    result = wifisetup.ConnectHomeNetwork(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\api\service.py", line 267, in __call__
    raise ActionException(msg) from last_exception
pywemo.exceptions.ActionException: Error communicating with WeMo Insight after 3 attempts. Giving up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pywemo\ouimeaux_device\__init__.py", line 472, in setup
    raise SetupException(
pywemo.exceptions.SetupException: pywemo lost device <WeMo Insight "WeMo Insight"> and was unable to reconnect.  Setup status is uncertain, re-probing and checking is required.
```
Do you know what might be causing this error message?

Also, now that I have the WeMo Insight V2 connected to Home Assistant I noticed that the device sensor isn't triggered when I have something like a camera plugged in.  What's the minimum power required for the sensor to be triggered.  Could this be adjusted to take into account devices that don't cosume too much power?

I have a camera connected and the sensor isn't triggered.
![image](https://user-images.githubusercontent.com/17913801/235515924-8612d7b4-7854-4470-a076-8cb110792ac1.png)

I tried my toaster and sensor was successfully triggered.

Thank you once again for all you help.

**Comment by Spectre5** [comment]
If the device connected to the network, then I think you can ignore that error.  I'm guessing that the device restarts after it successfully connects to the network which makes pywemo lose its connection.

**Comment by esev** [comment]
I believe the Insight devices default to using an 8 Watt threshold for determining if the connected device is On or Off. That can be changed though. It looks like a value of 1 Watt would be better for your camera. Here is an example of how to change the threshold with pyWeMo. Keep in mind that the threshold values are in milliwatts.

```python
import pywemo

WEMO_IP = '192.168.100.1' # Change this

wemo = pywemo.discovery.device_from_description(
    pywemo.discovery.setup_url_for_address(WEMO_IP, 0), None
)

threshold = wemo.insight.GetPowerThreshold()['PowerThreshold']
print(f'Current power threshold: {threshold} milliwatts ({float(threshold)/1000.0} Watts)')

wemo.insight.SetPowerThreshold(PowerThreshold=1000)  # Set to 1 Watt.
```
