### ISSUE TITLE
Fix Bridge xml handling

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#440]
Found these issues while fuzzing with [Atheris](https://github.com/google/atheris). Add the following two examples to `tests/test_registry_notify_fuzz.py` and resolve the root issues that they surface. Note, these examples require #441.

```python
@example(
    name="Bridge",
    properties=[
        (
            ConvertChildrenToText("StatusChange"),
            [
                (
                    "StateEvent",
                    [
                        ("DeviceID", "0017880108DA898B"),
                        ("CapabilityId", "10006"),
                        ("Value", "m50"),
                    ],
                )
            ],
        )
    ],
)
@example(
    name="Bridge",
    properties=[
        (
            ConvertChildrenToText("StatusChange"),
            [
                (
                    "StateEvent",
                    [
                        ("Value", "1"),
                        ("DeviceID", "F0D1B8000001420C"),
                        ("CapabilityId", "10008"),
                    ],
                )
            ],
        )
    ],
)
```

**Comment by esev** [comment]
The CI on #441 uncovered another issue with the Bridge device.
```
[('attribute', '-1'),
     (<StatusChange>,
      [('StateEvent',
        [('DeviceID', '0017880108DA898B'),
         ('CapabilityId', '10006'),
         ('Value', '-1')])])]
```


```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57830)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/http/server.py", line 420, in handle_one_request
    method()
  File "/home/runner/work/pywemo/pywemo/pywemo/subscribe.py", line 379, in do_NOTIFY
    outer.event(
  File "/home/runner/work/pywemo/pywemo/pywemo/subscribe.py", line 618, in event
    callback(device, type_, value)
  File "/home/runner/work/pywemo/pywemo/tests/test_registry_notify_fuzz.py", line 387, in callback
    device.subscription_update(type_, value)
  File "/home/runner/work/pywemo/pywemo/pywemo/ouimeaux_device/bridge.py", line 140, in subscription_update
    return self.lights[key].subscription_update(state_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pywemo/pywemo/pywemo/ouimeaux_device/bridge.py", line 279, in subscription_update
    LinkedDevice.update_state(self, {})
  File "/home/runner/work/pywemo/pywemo/pywemo/ouimeaux_device/bridge.py", line 241, in update_state
    self.state["level"] = status["levelcontrol"][0]
                          ~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable
----------------------------------------
```

This might require a  few different steps:

1. Make the device unavailable.  All the state change checks are skipped when the device is unavailable.
https://github.com/pywemo/pywemo/blob/bd540a56d63c89fe6c0432141a463232b635f363/pywemo/ouimeaux_device/bridge.py#L232-L235

```python
@example(
    name="Bridge",
    properties=[
        (
            ConvertChildrenToText("StatusChange"),
            [
                (
                    "StateEvent",
                    [
                        (ElementWithAttributes("DeviceID", {"available": "NO"}), "0017880108DA898B"),
                    ],
                )
            ],
        )
    ],
)
```

2. Change the levelcontrol to something invalid.
```python
@example(
    name="Bridge",
    properties=[
        (
            ConvertChildrenToText("StatusChange"),
            [
                (
                    "StateEvent",
                    [
                        ("DeviceID", "0017880108DA898B"),
                        ("CapabilityId", "10008"),
                        ("Value", "-1"),
                    ],
                )
            ],
        )
    ],
```

3. Turn the light on. This makes the state change checks apply again and then the invalid levelcontrol is noticed.
```python
@example(
    name="Bridge",
    properties=[
        (
            ConvertChildrenToText("StatusChange"),
            [
                (
                    "StateEvent",
                    [
                        ("DeviceID", "0017880108DA898B"),
                        ("CapabilityId", "10006"),
                        ("Value", "1"),
                    ],
                )
            ],
        )
    ],
)
```
