### ISSUE TITLE
Trying to use as a command line interface for Fauxmo. 

### ISSUE THREAD

**Issue by sisensee** [pywemo/pywemo#45]
Would like to use this to control Fauxmo devices (raspberry pi). Fauxmo has limited setup.xml natively.
Wrote GPIO handler for Fauxmo ([https://github.com/n8henrie/fauxmo](https://github.com/n8henrie/fauxmo)) to control GPIO via Amazon echo, also want to have physical button to turn on/off. Tried to modify Fauxmo protocol to present full Wemo setup.xml but getting time out error. Is it possible to modify to discover fauxmo devices?

**Comment by pavoni** [comment]
Would suggest you avoid ssdp discovery (if you aren't already) as described here
https://github.com/pavoni/pywemo#if-discovery-doesnt-work-on-your-network

Can you post the detailed timeout you're getting - may give some clues as to what isn't working.

**Comment by sisensee** [comment]
Unfortunately even the method you mentioned isn't working for me. Here is the output. I had to modify the commands a little as well. 

> > > import pywemo
> > > address = "192.168.1.105"
> > > port = pywemo.ouimeaux_device.probe_wemo(address)
> > > url = 'http://%s:%i/setup.xml' % (address, port)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: %i format: a number is required, not NoneType
> > > device = pywemo.discovery.device_from_description(url, None)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > NameError: name 'url' is not defined
> > > url = 'http://192.168.1.105:12341'
> > > device = pywemo.discovery.device_from_description(url, None)
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
> > >     httplib_response = conn.getresponse(buffering=True)
> > > TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.105', port=12341): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/pywemo/pywemo/discovery.py", line 37, in device_from_description
    xml = requests.get(description_url, timeout=30)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.105', port=12341): Read timed out. (read timeout=30)


The debug from fauxmo is:
2016-05-18 14:23:05 fauxmo:38       DEBUG    Connection made with: ('192.168.1.105', 33279)
2016-05-18 14:23:05 fauxmo:46       DEBUG    Received message:
GET / HTTP/1.1
Host: 192.168.1.105:12341
Accept: _/_
User-Agent: python-requests/2.9.1
Accept-Encoding: gzip, deflate
Connection: keep-alive

On thing I note is that the Connection: Keep-alive is different from normal Wemo communication. For the record this works with my actual Wemo switch. Perfectly actually so thank you VERY much!

**Comment by pavoni** [comment]
So it looks like Fauxmo isn't responding to `pywemo.ouimeaux_device.probe_wemo(address)` like a real WeMo which isn't really a surprise. 

From a quick look at Fauxmo - you configure the port - so just use the same port as you configured into Fauxmo.

So try `port = xxx`(where xxx is your Fauxmo port) instead of using probe.

**Comment by sisensee** [comment]
Specifying the port does give me a different error: 

> > > import pywemo
> > > address = "192.168.1.105"
> > > port = 12341
> > > url = 'http://192.168.1.105:12341/setup.xml'
> > > device = pywemo.discovery.device_from_description(url, None)
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
> > >     httplib_response = conn.getresponse(buffering=True)
> > > TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.105', port=12341): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/pywemo/pywemo/discovery.py", line 39, in device_from_description
    return device_from_uuid_and_location(uuid, mac, description_url)
  File "/home/pi/pywemo/pywemo/discovery.py", line 45, in device_from_uuid_and_location
    return Switch(location, mac)
  File "/home/pi/pywemo/pywemo/ouimeaux_device/**init**.py", line 67, in **init**
    service = Service(self, svc, base_url)
  File "/home/pi/pywemo/pywemo/ouimeaux_device/api/service.py", line 81, in **init**
    xml = requests.get(url, timeout=10)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.105', port=12341): Read timed out. (read timeout=10)

> > > print(device)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > NameError: name 'device' is not defined

I am not sure where its looking for name 'device', I know theres the device in setup.xml. I believe the issue is the way that fauxmo is presenting the setup.xml. It shows up like this. 
![screen shot 2016-05-19 at 3 02 04 pm](https://cloud.githubusercontent.com/assets/1280696/15412820/c983d764-1ddf-11e6-89d6-35f6c198826d.png)

I will try to get the browser to display the setup.xml from my Wemo when I get home.

**Comment by pavoni** [comment]
My guess is the URL being created [here](https://github.com/pavoni/pywemo/blob/master/pywemo/ouimeaux_device/api/service.py#L80) isn't correct - and is then timing out. You could trace it which might give you some clues as to what is wrong with service.xml.

**Comment by pavoni** [comment]
I'm going to close this - not really something I can support.
