### ISSUE TITLE
UnicodeDecodeError prevents home-assistant integration from initializing

### ISSUE THREAD

**Issue by jfroy** [pywemo/pywemo#716]
I've filed a bug on home-assistant (home-assistant/core/issues/109619), but also filing one here in case pywemo also needs to be more resilient. I don't have debug logs to share, but I'll try to get more information.

home-assistant core: 2024.2.5
home-assistant supervisor: 2024.02.1
home-assistant os: 12.0

```Logger: homeassistant.setup
Source: setup.py:333
First occurred: 09:18:07 (1 occurrences)
Last logged: 09:18:07

Error during setup of component wemo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 88, in async_setup
    await hass.async_add_executor_job(registry.start)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywemo/subscribe.py", line 716, in start
    self._httpd = _start_server(self._requested_port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywemo/subscribe.py", line 342, in _start_server
    return HTTPServer(("", port), RequestHandler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 795, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
                                 ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 8: invalid start byte
```

**Comment by jaharkes** [comment]
The problem here is that the host name of the system is set to something that is not allowed and cannot be looked up through DNS. When pywemo tries to start a small HTTP server, probably as an API endpoint, and it tries to find the network address by asking which network address is associated with its own host name.

Valid names for hosts in DNS are actually very restrictive and defined in [RFC1035](https://www.rfc-editor.org/rfc/rfc1035)

Briefly it looks like this, there are only 63 allowed characters
- the 52 upper and lower case alphabetic characters [a-zA-Z]
- the 10 digits [0-9]
- the hyphen character "-"

And on top of that the name _has_ to start with an alphabetic letter, may not end with a hyphen, and must be 63 characters or less in length.

Ultimately the host name of any computer that needs to have it's name looked up is bound by these naming restrictions, although nothing is enforcing the restrictions when you set /etc/hostname problems appear as soon as your machine needs to be addressed by name on a network, such as when initializing this pywemo API endpoint.

**Comment by esev** [comment]
I believe this is the Python bug described here: https://github.com/python/cpython/issues/53623#issuecomment-1093513009. The "_more complex sample_" from that comment is the same logic used in pyWeMo here https://github.com/pywemo/pywemo/blob/22b431a54f695cddddf4be7a04e0232c8a9fd8de/pywemo/subscribe.py#L342

The ("", port) syntax is described here https://docs.python.org/3/library/socket.html#host-port
> '' represents INADDR_ANY, which is used to bind to all interfaces

pyWeMo needs to bind to all interfaces. Passing a specific hostname wouldn't work as there could be multiple interfaces used on the host.

Does anyone know of a workaround for this bug?

**Comment by esev** [comment]
The error occurs [here](https://github.com/python/cpython/blob/b9cb855621c0813846421e4ced97260a32e57063/Lib/http/server.py#L138) in the Python code which seems to be after the point where the bind actually takes place. pyWeMo doesn't use either `server_name` or `server_port`.  But we don't control cpython either, which may introduce code that relies on these two properties (or adds more). I suspect the diff below may handle the issue, but it also has a potential to break things depending on how cpython changes.

```diff
diff --git a/pywemo/subscribe.py b/pywemo/subscribe.py
index 6e3ffce..82fd804 100644
--- a/pywemo/subscribe.py
+++ b/pywemo/subscribe.py
@@ -325,6 +325,20 @@ class HTTPServer(ThreadingHTTPServer):
 
     outer: SubscriptionRegistry
 
+    def server_bind(self) -> None:
+        """Override server_bind to work around cpython bug.
+        
+        https://github.com/python/cpython/issues/53623
+        https://github.com/pywemo/pywemo/issues/716
+        """
+        try:
+            super().server_bind()
+        except UnicodeDecodeError as err:
+            LOG.info(
+                "Ignoring github.com/python/cpython/issues/53623 bug: %s", err
+            )
+            pass
+
 
 def _start_server(port: int | None) -> HTTPServer:
     """Find a valid open port and start the HTTP server."""
```

I'd rather not implement this hack/workaround. It seems brittle, depending too much on the internal behavior of cpython, which pyWeMo does not control.

I'll leave this bug open for a while. Let's see if there are better solutions. It may be that we need to close this bug though. A cleaner solution should come from Python itself.
