### ISSUE TITLE
Issue with Wemo Switch Mini

### ISSUE THREAD

**Issue by lolento** [pywemo/pywemo#79]
Hello,

I'm consistently getting this error in Home Assistant with a Wemo Mini Switch:

2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Error during setup of component wemo
Traceback (most recent call last):
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 302, in _error_catcher
    yield
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 384, in read
    data = self._fp.read(amt)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 448, in read
    n = self.readinto(b)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 747, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.2.160', port=49153): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\homeassistant\setup.py", line 194, in _async_setup_component
    component.setup, hass, processed_config)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\homeassistant\components\wemo.py", line 97, in setup
    device = pywemo.discovery.device_from_description(url, None)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywemo\discovery.py", line 40, in device_from_description
    return device_from_uuid_and_location(uuid, mac, description_url)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywemo\discovery.py", line 46, in device_from_uuid_and_location
    return Switch(location, mac)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywemo\ouimeaux_device\__init__.py", line 63, in __init__
    xml = requests.get(url, timeout=10)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 652, in send
    r.content
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 825, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Users\Hilman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 754, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.2.160', port=49153): Read timed out.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-07-31 15:40:15 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.

**Comment by pavoni** [comment]
It looks like it's having trouble talking to one of your devices (I think 192.160.2.160).

Worth making sure you have the latest firmware (update via the wemo app).

Also worth trying to power off and on the switch.

Afraid I don't have a wemo mini switch - so I'm not 100% whether the code works with it.

**Comment by lolento** [comment]
Hey Greg,


Yes, thanks for the quick reply.  Yes, the Wemo Mini is on the latest firmware.


Usually, unplugging and replugging the switch helps but not always....  Simply powering off and on does not.


________________________________

**Comment by lolento** [comment]
Hi Greg,

Keep playing with the Wemo Mini, it looks like in general it takes a long time for the Mini to respond back with the setup.xml.

My insight switches responds pretty quickly.  

Is there a set time-out you're using?

**Comment by pavoni** [comment]
Code I inherited rather than wrote - but it's here.
https://github.com/pavoni/pywemo/blob/master/pywemo/ssdp.py

Have never investigated in detail.

You can code the IP address manually to see of that works.
 See https://github.com/pavoni/pywemo - `If discovery doesn't work on your network`

**Comment by pavoni** [comment]
@lolento Did you make any progress with this?

**Comment by angel12** [comment]
I have a wemo switch mini, and have not seen this particular issue, but I have not had it for more than 2 weeks.

**Comment by lolento** [comment]
Yes, I'm still having issue with the Mini, it's been hit or miss but mostly miss...

@angel12, what is your setup like?

**Comment by pavoni** [comment]
@lolento discovery can be shaky on some networks (including mine) - I now explicitly list the IP addresses which is much more reliable (details here https://github.com/pavoni/pywemo under `If discovery doesn't work on your network `).

On the basis that it sometimes works I suspect the mini is just like other wemo devices - so I'm going to close this. Happy to re-open as needed.
