### ISSUE TITLE
Issue with Dimmer switch

### ISSUE THREAD

**Issue by angel12** [pywemo/pywemo#85]
Currently, after calling get_brightness on device once, you cannot call it again. This is the error I am getting now:

```
>>> device.get_brightness()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "*wemo dimmer\pywemo-master\pywemo\ouimeaux_device\dimmer.py", line 18, in get_brightness
    self._brightness = brightness
UnboundLocalError: local variable 'brightness' referenced before assignment
```

**Comment by pavoni** [comment]
You need to put the assignment inside the if test

```
        if force_update or self._brightness is None:
            try:
                brightness = self.basicevent.GetBinaryState().get('brightness')
            except ValueError:
                brightness = 0
            self._brightness = brightness

        return self._brightness
```

Happy to release if you  an test and send a PR.

Sorry I missed this!

**Comment by angel12** [comment]
Hmm, even with those changes I am still getting this error. 

```
>>> device.get_brightness()
'80'
>>> device.set_brightness(25)
>>> device.get_brightness()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\shares\spencer\wemo dimmer\pywemo-master\pywemo\ouimeaux_device\dimmer.py", line 17, in get_brightness
    self._brightness = brightness
UnboundLocalError: local variable 'brightness' referenced before assignment
>>>
```


Current get_brightness:
```
    def get_brightness(self, force_update=False):
        """
        Get Brightness From Device
        """
        if force_update or self._brightness is None:
            try:
                brightness = self.basicevent.GetBinaryState().get('brightness')
            except ValueError:
                brightness = 0
        self._brightness = brightness

        return self._brightness

```


Edit: 
Here it works, kind of:
```
    def get_brightness(self, force_update=False):
        """
        Get Brightness From Device
        """
        global brightness
        if force_update or self._brightness is None:
            try:
                brightness = self.basicevent.GetBinaryState().get('brightness')
            except ValueError:
                level = 0
        self._brightness = brightness
```

```
>>> device.get_brightness()
'25'
>>> device.set_brightness(50)
>>> device.get_brightness()
'25'
>>> device.basicevent.GetBinaryState().get('brightness')
'50'
>>>
```

But the get_brightness function didn't pull the new value, which I am assuming has to do with subscription? I had to get the brightness from scratch, since self._brightness already had the value cached

**Comment by pavoni** [comment]
Looks like you didn't indent the `self._brightness = brightness` line to start at the same column as the expect.

Python is sensitive to indentation - so it's currently executing the assignment even if you didn't drop into the if test (which you don't want).

So you want the code to look like:-

```
    def get_brightness(self, force_update=False):
        """
        Get Brightness From Device
        """
        if force_update or self._brightness is None:
            try:
                brightness = self.basicevent.GetBinaryState().get('brightness')
            except ValueError:
                brightness = 0
            self._brightness = brightness  # NOTE INDENTATION HERE

        return self._brightness
```

**Comment by angel12** [comment]
Well, I don't know what happened during my tests, but now I am not seeing the brightness updated when I use the app. I have added a new function get_wlevel that does this correctly, but I am not sure if the code I used is how we should be doing it. Here it is:

```
    def get_brightness(self, force_update=False):
        """
        Get Brightness From Device
        """
        if force_update or self._brightness is None:
            try:
                brightness = self.basicevent.GetBinaryState().get('brightness')
            except ValueError:
                brightness = 0
            self._brightness = brightness

        return self._brightness

    def get_wlevel(self, force_update=False):
        """
        Get Brightness From Device
        """
        try:
            wlevel = self.basicevent.GetBinaryState().get('brightness')
        except ValueError:
            wlevel = 0
        self._brightness = wlevel

        return self._brightness
```

Theoretically, if my code is ok, I could just replace wlevel with brightness and remove my original one

**Comment by pavoni** [comment]
It's because we're now caching the brightness (which is mostly a good thing).

If you want to refresh the state you need to call `device.get_brightness(True)`

It means you can be more controlled about when this happens (which is what the other HA wemo devices do).

You can see an example here https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/wemo.py#L209
