### ISSUE TITLE
Invalid Config for Wemo

### ISSUE THREAD

**Issue by Coolie1101** [pywemo/pywemo#90]
2017-12-07 17:41:46 ERROR (MainThread) [homeassistant.setup] Error during setup of component wemo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.200.123', port=49153): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 193, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/wemo.py", line 89, in setup
    port = pywemo.ouimeaux_device.probe_wemo(address)
  File "/srv/homeassistant/lib/python3.5/site-packages/pywemo/ouimeaux_device/__init__.py", line 30, in probe_wemo
    timeout=10)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.200.123', port=49153): Read timed out. (read timeout=10)
2017-12-07 17:41:55 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-12-07 17:41:55 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.
2017-12-07 17:41:55 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of switch.wemo. Setup failed for dependencies: wemo
2017-12-07 17:41:55 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.wemo: Could not setup all dependencies.

**Comment by Coolie1101** [comment]
I uninstalled pywemo and now get the following error after restarting HA.

2017-12-07 17:49:45 ERROR (MainThread) [homeassistant.setup] Error during setup of component wemo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.200.123', port=49153): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 193, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/wemo.py", line 89, in setup
    port = pywemo.ouimeaux_device.probe_wemo(address)
  File "/srv/homeassistant/lib/python3.5/site-packages/pywemo/ouimeaux_device/__init__.py", line 30, in probe_wemo
    timeout=10)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.200.123', port=49153): Read timed out. (read timeout=10)
2017-12-07 17:49:45 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service_data=notification_id=invalid_config, title=Invalid config, message=The following components and platforms could not be set up:

 - [wemo](https://home-assistant.io/components/wemo/)

**Comment by angel12** [comment]
@Coolie1101  This looks to be a bug in HASS 59.2; as I just started getting these errors when I upgraded. Have you posted this issue there?

edit: actually, I can't test this theory right now, but you wouldn't happen to have an insight, would you?

**Comment by angel12** [comment]
@Coolie1101  what OS are you running HASS on?

**Comment by Coolie1101** [comment]
1. Yes issue was posted.
2. No insigt's
3. Hassbian

**Comment by angel12** [comment]
What I am seeing right now is when running Ubuntu 17.10, I get these errors, but on ubuntu 17.04 I am not. Really strange.

**Comment by jimloki** [comment]
As I said on HA forum:

After a power failure today, all my wemo came back!!! (I’m still using hassbian). So I don’t know where the problem is. I previously rebooted the raspberry pi several times with no success…

They are all accessible on port 49153. When it didn’t work, [homeassistant.components.discovery] could find them on port 49153 or 49154

I have this problem since HA version 0.57.3 (and maybe before, I don't remember, I don't have older logs)

I don't have insight, only switches and a motion sensor

**Comment by Coolie1101** [comment]
Tried resetting the power by turning of the breaker at the electrical panel, but still the same.

**Comment by Coolie1101** [comment]
Issue resolved.

Been digging around with the Wemo app and HASS since my last post, un-install and re-installed the app, deleted all devices, re-added all devices, changed WiFi, changed names, added one device at a time while rebooting HASS, but was still unsuccessful.

After a couple hours, I just gave up and decided that I would just rely on the app to control the switches, while adding the device back into the app for the last time, I got a firmware update notification after adding the fourth device went ahead and did the update, continued adding the remainder devices, after everything was added and working, I decided to reboot HASS again just for the hell of it, after all what's the worst that can happen, and what do you know, all switches are recognized and configured in HASS, and functioning, even my previously configured automation's worked.
![image](https://user-images.githubusercontent.com/28989417/33858743-f09134ec-de9e-11e7-8807-715e8abcf795.png)

**Comment by jimloki** [comment]
My wemos are already on 2.0010966 firmware version, so I’m not sure it’s the solution

**Comment by Norien** [comment]
I don't have much to add but I am having the same problem. Just switched my config over from a working Ubuntu 17.04 with home assistant in venv 0.59.2 & 6 working wemo devices to a brand new Ubuntu 17.10 box with fresh home assistant in venv 0.59.2 copied config over.

- All firmwares are up to date
- Tried cutting power to wemo devices for half hour / no go
- all wemo devices work on native app ok
- can ping all devices as home assistant user

**Comment by angel12** [comment]
Seems to be a weird hit or miss issue, sometimes it all works fine on the latest ubuntu, sometimes it doesnt. I dont have any time really to dig deeper into it though
