### ISSUE TITLE
Unhandled HTTPConnectionPool error

### ISSUE THREAD

**Issue by ViViDboarder** [pywemo/pywemo#93]
I noticed this while running Home Assistant with version 0.4.20.

I was seeing the error documented in #90 and started drilling down.
```
home_assistant | ERROR:homeassistant.setup:Error during setup of component wemo
home_assistant | Traceback (most recent call last):
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
home_assistant |     six.raise_from(e, None)
home_assistant |   File "<string>", line 2, in raise_from
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
home_assistant |     httplib_response = conn.getresponse()
home_assistant |   File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
home_assistant |     response.begin()
home_assistant |   File "/usr/lib/python3.5/http/client.py", line 297, in begin
home_assistant |     version, status, reason = self._read_status()
home_assistant |   File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
home_assistant |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
home_assistant |   File "/usr/lib/python3.5/socket.py", line 576, in readinto
home_assistant |     return self._sock.recv_into(b)
home_assistant | socket.timeout: timed out
home_assistant |
home_assistant | During handling of the above exception, another exception occurred:
home_assistant |
home_assistant | Traceback (most recent call last):
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
home_assistant |     timeout=timeout
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
home_assistant |     _stacktrace=sys.exc_info()[2])
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
home_assistant |     raise six.reraise(type(error), error, _stacktrace)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 686, in reraise
home_assistant |     raise value
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
home_assistant |     chunked=chunked)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
home_assistant |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
home_assistant |     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
home_assistant | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.2.3', port=49153): Read timed out. (read timeout=10)
home_assistant |
home_assistant | During handling of the above exception, another exception occurred:
home_assistant |
home_assistant | Traceback (most recent call last):
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/homeassistant/setup.py", line 193, in _async_setup_component
home_assistant |     component.setup, hass, processed_config)
home_assistant |   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
home_assistant |     yield self  # This tells Task to wait for completion.
home_assistant |   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
home_assistant |     future.result()
home_assistant |   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
home_assistant |     raise self._exception
home_assistant |   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
home_assistant |     result = self.fn(*self.args, **self.kwargs)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/wemo.py", line 89, in setup
home_assistant |     port = pywemo.ouimeaux_device.probe_wemo(address)
home_assistant |   File "/config/deps/lib/python3.5/site-packages/pywemo/ouimeaux_device/__init__.py", line 29, in probe_wemo
home_assistant |     timeout=10)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 72, in get
home_assistant |     return request('get', url, params=params, **kwargs)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
home_assistant |     return session.request(method=method, url=url, **kwargs)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
home_assistant |     resp = self.send(prep, **send_kwargs)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
home_assistant |     r = adapter.send(request, **kwargs)
home_assistant |   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 521, in send
home_assistant |     raise ReadTimeout(e, request=request)
home_assistant | requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.2.3', port=49153): Read timed out. (read timeout=10)
```

The strange thing about that log is that it shows that requests is taking the `HTTPConnectionPool` error and raising it again as a `ReadTimeout`. I noted that in `requests`, `ReadTimeout` is a subclass of `requests.exceptions.Timeout` and that this is supposedly being handled  on [line 39](https://github.com/pavoni/pywemo/blob/master/pywemo/ouimeaux_device/__init__.py#L39).

I added another handler at the bottom of the list as a catch all as:

```
except Exception as e:
    log.info('Unknown error %s from %s on port %i, continuing',
              repr(e), host, port)
    log.info('Exception class %s', e.__class__)
    log.info('Is instance of requests.exceptions.Timeout? %r',
            isinstance(e, requests.exceptions.Timeout))
    log.info('Is instance of requests.exceptions.ConnectionError? %r',
            isinstance(e, requests.exceptions.ConnectionError))
```

This ends up catching and logging

```
home_assistant | INFO:pywemo.ouimeaux_device:Unknown error ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='192.168.2.3', port=49153): Read timed out. (read timeout=10)",),) f
rom 192.168.2.3 on port 49153, continuing
home_assistant | INFO:pywemo.ouimeaux_device:Exception class <class 'requests.exceptions.ReadTimeout'>
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.Timeout? False
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.ConnectionError? False
home_assistant | INFO:pywemo.ouimeaux_device:Unknown error ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.2.3', port=49152): Max retries exceeded with url: /setup.x
ml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x671d3af0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),) from 192.16
8.2.3 on port 49152, continuing
home_assistant | INFO:pywemo.ouimeaux_device:Exception class <class 'requests.exceptions.ConnectionError'>
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.Timeout? False
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.ConnectionError? False
home_assistant | INFO:pywemo.ouimeaux_device:Unknown error ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.2.3', port=49154): Max retries exceeded with url: /setup.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x64f2b4d0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),) from 192.16
8.2.3 on port 49154, continuing
home_assistant | INFO:pywemo.ouimeaux_device:Exception class <class 'requests.exceptions.ConnectionError'>
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.Timeout? False
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.ConnectionError? False
home_assistant | INFO:pywemo.ouimeaux_device:Unknown error ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.2.3', port=49151): Max retries exceeded with url: /setup.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x64ec24b0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),) from 192.16
8.2.3 on port 49151, continuing
home_assistant | INFO:pywemo.ouimeaux_device:Exception class <class 'requests.exceptions.ConnectionError'>
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.Timeout? False
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of requests.exceptions.ConnectionError? False
```

Which has me totally stumped as I can see clearly that it's telling me that a `requests.exceptions.ConnectionError` is not an instance of `requests.exceptions.ConnectionError`...

At this point I want to yank my hair out. I even did a sanity check and verify with `inspect.getfile(e.__class__)` and `inspect.getfile(requests.exceptions.Timeout)` are referencing the exact same file path.

**Comment by ViViDboarder** [comment]
Found a similar error someone had on Stack Exchange: https://stackoverflow.com/questions/46715586/isinstance-unexpectedly-returning-false

**Comment by ViViDboarder** [comment]
Got something!

Updated my handler to:

```
        except Exception as e:
            log.info('Unknown error %s from %s on port %i, continuing',
                      repr(e), host, port)
            log.info('Exception class %s', e.__class__)
            log.info('Is instance of %s? %r',
                    repr(requests.exceptions.Timeout),
                    isinstance(e, requests.exceptions.Timeout))
            log.info('Is instance of %s? %r',
                    repr(requests.exceptions.ConnectionError),
                    isinstance(e, requests.exceptions.ConnectionError))
            log.info('Exception file path %s', inspect.getfile(e.__class__))
            log.info('Caught exceptions filepath %s', inspect.getfile(requests.exceptions.Timeout))
```

And the result is:

```
home_assistant | INFO:pywemo.ouimeaux_device:Unknown error ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='192.168.2.3', port=49153): Read timed out. (read timeout=10)",),) f
rom 192.168.2.3 on port 49153, continuing
home_assistant | INFO:pywemo.ouimeaux_device:Exception class <class 'requests.exceptions.ReadTimeout'>
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of <class 'pip._vendor.requests.exceptions.Timeout'>? False
home_assistant | INFO:pywemo.ouimeaux_device:Is instance of <class 'pip._vendor.requests.exceptions.ConnectionError'>? False
home_assistant | INFO:pywemo.ouimeaux_device:Exception file path /usr/local/lib/python3.5/dist-packages/requests/exceptions.py
home_assistant | INFO:pywemo.ouimeaux_device:Caught exceptions filepath /usr/local/lib/python3.5/dist-packages/requests/exceptions.py
```

Despite pointing to the same file through inspect, they are members of different modules!

Still not sure why or how to fix yet.

**Comment by ViViDboarder** [comment]
I modified the module to import all the errors directly rather than referencing from `requests.exceptions` and it works! However I'm still very confused as to why...
